version: "3.9"
services:
        tomcat:
                image: "tomcat_book:latest"
                build:
                        context: .
                        dockerfile: Dockerfile
                environment:
                  JAVA_OPTS: "-DDB_USER=${DB_USER} -DDB_PWD=${DB_PWD}"
                ports:
                        - "80:30000"
                networks:
                        - book-net
                depends_on: 
                        - mysql
        mysql:
                image: "mysql"
                environment: 
                  - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
                volumes:
                        - mysql:/var/lib/mysql
                        - ./mysql:/docker-entrypoint-initdb.d
                networks:
                        - book-net
networks:
        book-net: {}
volumes:
        mysql: {}
