version: "3.9"
services:
        tomcat:
                image: "tomcat_book:latest"
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - "8080:8080"
                networks:
                        - book-net
                depends_on: 
                        - mysql
        mysql:
                image: "mysql_book:latest"
                build:
                        context: ./mysql
                        dockerfile: Dockerfile_mysql
                volumes:
                        - mysql:/var/lib/mysql
                networks:
                        - book-net
networks:
        book-net: {}
volumes:
        mysql: {}
