apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-ss
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: book
    app: mysql #label to find the respective pods to manage
spec:
  serviceName: "mysql"
  replicas: 1 #create 1 replicas
  selector:
    matchLabels:
      app: mysql #select mysql app
  template: #template for the replica/pod specification
    metadata:
      labels:
        app: mysql #label for the corresponding app
    spec: #replica spec part
      containers:
      - name: mysql #container name
        image: mysql #container image
        env: #get MySQL root password from specific secret
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: db-secret
               key: password
        ports:
        - containerPort: 3306 #container port
        volumeMounts: #mounting of two volumes
          - name: mysql-vol
            mountPath: /var/lib/mysql
          - name: init
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-vol #first volume maps to a claim
          persistentVolumeClaim:
            claimName: mysql-claim 
        - name: init #second volume maps to a secret that incorporates the script.sql file
          secret:
            secretName: sql-secret
