apiVersion: v1
kind: PersistentVolume 
metadata:
  name: pv-mysql
  labels:
    app: mysql #maps to mysql app
spec: #perfectly matches mysql_claim.yaml
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mysql/
