apiVersion: apps/v1
kind: Deployment #Deployment kind
metadata:
  name: book #Deployment name
  labels:
    app: book #label to find the respective pods to manage
spec:
  replicas: 2 #create 2 replicas
  selector:
    matchLabels:
      app: book #select nginx app
  template: #template for the replica/pod specification
    metadata:
      labels:
        app: book #label for the corresponding app
    spec: #replica spec part
      nodeSelector:
        componentType: APP
      containers:
      - name: book #container name
        image: kkritikos/book:latest-stable #container image
        ports:
        - containerPort: 30000 #container port
        env:
         - name: DB_USER
           valueFrom:
             secretKeyRef:
               name: user-secret
               key: username
         - name: DB_PWD
           valueFrom:
             secretKeyRef:
               name: user-secret
               key: password
         - name: JAVA_OPTS
           value: "-DDB_USER=$(DB_USER) -DDB_PWD=$(DB_PWD)"
